services:
  traefik:
    container_name: traefik
    hostname: traefik
    image: traefik:v3.6.7
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --certificatesresolvers.le.acme.email=luizomf@gmail.com
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --log.level=INFO
      - --accesslog=true
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
    restart: unless-stopped

  api:
    hostname: api
    build:
      context: ../api
    depends_on:
      - alloy
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4317
      - OTEL_SERVICE_NAME=lgtm-demo-api
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.inprod.cloud`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=le
      - traefik.http.routers.api.priority=100
      - traefik.http.services.api.loadbalancer.server.port=8000

    restart: unless-stopped

  loki:
    hostname: loki
    image: grafana/loki:3.6.7
    restart: unless-stopped
    volumes:
      - loki-data:/loki
      - ./loki-config.yaml:/etc/loki/config.yaml:ro
    command: ['-config.file=/etc/loki/config.yaml']

  grafana:
    hostname: grafana
    image: grafana/grafana:12.4.0
    ports:
      - 10.100.0.2:3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWD:-admin}
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources/default.yaml:/etc/grafana/provisioning/datasources/default.yaml:ro
      - ./grafana/provisioning/dashboards/default.yaml:/etc/grafana/provisioning/dashboards/default.yaml:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.lgtm.rule=Host(`lgtm.inprod.cloud`)
      - traefik.http.routers.lgtm.entrypoints=websecure
      - traefik.http.routers.lgtm.tls=true
      - traefik.http.routers.lgtm.tls.certresolver=le
      - traefik.http.routers.lgtm.priority=100
      - traefik.http.routers.lgtm.middlewares=grafana-allow
      - traefik.http.middlewares.grafana-allow.ipallowlist.sourcerange=10.100.0.0/24,187.108.118.25/32
      - traefik.http.services.lgtm.loadbalancer.server.port=3000

  tempo:
    hostname: tempo
    image: grafana/tempo:2.10.1
    command: ['-config.file=/etc/tempo/config.yaml']
    restart: unless-stopped
    volumes:
      - tempo-data:/var/tempo
      - ./tempo-config.yaml:/etc/tempo/config.yaml:ro

  mimir:
    container_name: mimir
    hostname: mimir
    image: grafana/mimir:2.17.7
    command: ['-config.file=/etc/mimir/config.yaml', '-target=all']
    restart: unless-stopped
    volumes:
      - mimir-data:/data/mimir
      - ./mimir-config.yaml:/etc/mimir/config.yaml:ro

  alloy:
    container_name: alloy
    hostname: alloy
    image: grafana/alloy:v1.12.0
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy
    restart: unless-stopped
    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  node-exporter:
    hostname: node-exporter
    image: quay.io/prometheus/node-exporter:v1.8.2
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/rootfs
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($|/)
      - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|nsfs|overlay|proc|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs|tmpfs)$
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro,rslave

volumes:
  grafana-data:
  loki-data:
  mimir-data:
  tempo-data:
  traefik_letsencrypt:
